#!/bin/bash

export TERM=xterm-256color

# Colors
red=`tput setaf 1`
green=`tput setaf 2`
yellow=`tput setaf 3`
blue=`tput setaf 4`
purple=`tput setaf 5`
cyan=`tput setaf 6`
white=`tput setaf 7`
orange=`tput setaf 208`
reset=`tput sgr0`

targetDate=`echo $1|sed 's/\//-/g'`
targetDay=`date -d $targetDate +%A`

cd ~/sshlogs
echo " "
echo "Log files for $targetDay, $targetDate"
echo ${green}
ls -hl $targetDate*| awk '{print $10"	"$6"	"$9}'
echo " "
echo ${reset}

read -p "Press [enter] to continue..."


echo " "
echo "Searching for commands issued on $targetDate" 
echo "========================================================================"

for i in `ls --color=none $targetDate*`
do
  search $i
done | more
