#!/bin/bash

# Get Mintty color schemes
shopt -s expand_aliases
source ~/.bash_mintty_colors

USERNAME=`whoami`
DATE=`date +%Y-%m-%d`
LOGDIR="${HOME}/sshlogs"
MACHINE=`hostname`

# Clip off the username, if provided, and keep the hostname
if [[ $1 == *"@"* ]]
then
  FULLHOST=`echo $1 | cut -d'@' -f 2`
  USERNAME=`echo $1 | cut -d'@' -f 1`
else
  FULLHOST=$1
fi

# Clip the hostname from the FQDN, DNS suffix-search will replace, if needed. 
if [[ $FULLHOST =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  HOST=$FULLHOST
else
  HOST=`echo $FULLHOST|cut -d'.' -f1`
fi

# Log ssh client activity via tee
ssh -X -Y $1 | tee -a $LOGDIR/$DATE-$MACHINE-$HOST.log

# Reset color scheme to default (grey on black)
default
