#!/bin/bash

export TERM=xterm-256color
export myid=`whoami`

# Colors!
red=`tput setaf 1`
redbg=`tput setab 197`
green=`tput setaf 2`
yellow=`tput setaf 3`
blue=`tput setaf 4`
niceblue=`tput setaf 27`
purple=`tput setaf 5`
cyan=`tput setaf 6`
white=`tput setaf 7`
orange=`tput setaf 208`
reset=`tput sgr0`

echo " "
echo "${orange}Commands entered for${reset} ${niceblue}$1${reset}"
echo "${purple}========================================================================${reset}"
egrep \
    "^\\[|^\\$" $1 \
    | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g" \
    | sed "s/[[:cntrl:]]//g" \
    | sed "s/\([0-2]\)\([0-9]\):\([0-5]\)\([0-9]\) \([AP]M\)/${green}\1\2:\3\4 \5${reset}/" \
    | sed "s/\(root\)/${red}\1${reset}/" \
    | sed "s/\($myid\)/${bold}${yellow}\1${reset}/" \
    | sed "s/\(\[C\)//g" \
    | sed "s/\(logout\)/\1\n${purple}........................................................................${reset}\n/"
echo "${purple}========================================================================${reset}"
