#!/usr/bin/bash

# Get Mintty color schemes
shopt -s expand_aliases
source ~/.bash_mintty_colors

USERNAME=`whoami`
DATE=`/usr/bin/date +%Y-%m-%d`
LOGDIR="/home/$USERNAME/sshlogs"
MACHINE=`/usr/bin/hostname`

# Create a unique session name for tmux tied to date and time
# This prevents tmux from attaching to an existing session
# should the detached command fail

sessionName=`date +%Y-%m-%d-%H-%M-%S`

# Test an IP address for validity:
# Usage:
#      valid_ip IP_ADDRESS
#      if [[ $? -eq 0 ]]; then echo good; else echo bad; fi
#   OR
#      if valid_ip IP_ADDRESS; then echo good; else echo bad; fi
#
# Credit: https://www.linuxjournal.com/content/validating-ip-address-bash-script
#
function valid_ip()
{
    local  ip=$1
    local  stat=1

    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
            && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat=$?
    fi
    return $stat
}

# Clip off the username, if provided, and capture the hostname
if [[ $1 == *"@"* ]]
then
 FULLHOST=`echo $1|/usr/bin/cut -d'@' -f 2`
 USERNAME=`echo $1|/usr/bin/cut -d'@' -f 1`
else
 FULLHOST=$1
fi

# Clip the hostname from the FQDN, DNS suffx-search will replace, if needed. 
if  ! valid_ip $ $HOST
then
  HOST=`echo $FULLHOST|cut -d'.' -f1`
fi

# Choose a Mintty color scheme based on the hostname
if [[ $HOST == "host1" || $HOST == "host2" || $HOST == "host3" || $HOST == "host4" || $HOST == "host5" || $HOST == "host6" ]]
then
 # Purple for Ansible control machines or Jenkins CI server
 purple
elif [[ $HOST == *"host7"* || $HOST == *"host8"* || $HOST == *"host9"* || $HOST == *"host10"* || $HOST == *"mdw01p"* ]]
then
 # Red color scheme: These servers are either in production or dangerous
red
elif [[ $HOST == *"host11"* || $HOST == *"host12"* || $HOST == *"host13"* || $HOST == *"host14"* || $HOST == *"host15"* ]]
then
 # Green color scheme: These servers are for development or testing
green
elif [[ $HOST == *"centos"* || $HOST == *"debian"* ]]
then
 # Blue color scheme: These servers are local virtial machines
blue
fi


# Set the label to the hostname
LABEL="$HOST"

# Set the label based on key hostnames
case "$HOST" in
 hostA)
     LABEL="Nice label for Host A"
	;;
 hostB)
     LABEL="Nice label for Host A"
	;;
 hostC)
     LABEL="Nice label for Host A"
	;;
 hostD)
     LABEL="Nice label for Host A"
	;;
esac

# Set Mintty title
echo -ne '\e]0;'$LABEL'\a'

# Wrap tmux around lssh
/usr/bin/tmux new -s $sessionName -n "$LABEL" -d lssh $USERNAME@$FULLHOST
/usr/bin/tmux attach

# Reset Mintty color scheme to default (grey on black)
default
